export const AllTopRentedItems = [
    {
        productId: 1,
        image: "https://picsum.photos/243/237",
        itemName: "Toyota Car",
        lender: "Saransh",
        place: "Gurgaon",
        oldPrice: 5000,
        currentPrice: 3500,
        duration: "week",
        rating: 4.8,
        slug: "toyota-car",
        productDetails: "The Toyota Car offers a comfortable ride and impressive fuel efficiency. Ideal for both city driving and longer trips, it’s equipped with modern features that enhance safety and convenience."
    },
    {
        productId: 2,
        image: "https://picsum.photos/242/237",
        itemName: "Hairdryer",
        lender: "Rakiul",
        place: "Malda",
        oldPrice: 1000,
        currentPrice: 800,
        duration: "week",
        rating: 4.9,
        slug: "hairdryer",
        productDetails: "This high-performance hairdryer features multiple heat and speed settings, ensuring a quick and efficient drying experience. Its lightweight design makes it easy to handle, while the sleek look adds style to your grooming routine."
    },
    {
        productId: 3,
        image: "https://picsum.photos/243/236",
        itemName: "Laptop",
        lender: "Dev",
        place: "Canada",
        oldPrice: 10000,
        currentPrice: 9500,
        duration: "day",
        rating: 4.7,
        slug: "laptop",
        productDetails: "This laptop is designed for productivity, offering powerful performance for both work and play. With a high-resolution display and fast processing speed, it's perfect for multitasking and running demanding applications."
    },
    {
        productId: 4,
        image: "https://picsum.photos/243/237",
        itemName: "Toyota Car",
        lender: "Saransh",
        place: "Gurgaon",
        oldPrice: 5000,
        currentPrice: 3500,
        duration: "week",
        rating: 4.8,
        slug: "toyota-car",
        productDetails: "The Toyota Car offers a comfortable ride and impressive fuel efficiency. Ideal for both city driving and longer trips, it’s equipped with modern features that enhance safety and convenience."
    },
    {
        productId: 5,
        image: "https://picsum.photos/242/237",
        itemName: "Hairdryer",
        lender: "Rakiul",
        place: "Malda",
        oldPrice: 1000,
        currentPrice: 800,
        duration: "week",
        rating: 4.9,
        slug: "hairdryer",
        productDetails: "This high-performance hairdryer features multiple heat and speed settings, ensuring a quick and efficient drying experience. Its lightweight design makes it easy to handle, while the sleek look adds style to your grooming routine."
    },
    {
        productId: 6,
        image: "https://picsum.photos/243/236",
        itemName: "Laptop",
        lender: "Dev",
        place: "Canada",
        oldPrice: 10000,
        currentPrice: 9500,
        duration: "day",
        rating: 4.7,
        slug: "laptop",
        productDetails: "This laptop is designed for productivity, offering powerful performance for both work and play. With a high-resolution display and fast processing speed, it's perfect for multitasking and running demanding applications."
    },
    {
        productId: 7,
        image: "https://picsum.photos/243/237",
        itemName: "Toyota Car",
        lender: "Saransh",
        place: "Gurgaon",
        oldPrice: 5000,
        currentPrice: 3500,
        duration: "week",
        rating: 4.8,
        slug: "toyota-car",
        productDetails: "The Toyota Car offers a comfortable ride and impressive fuel efficiency. Ideal for both city driving and longer trips, it’s equipped with modern features that enhance safety and convenience."
    },
    {
        productId: 8,
        image: "https://picsum.photos/242/237",
        itemName: "Hairdryer",
        lender: "Rakiul",
        place: "Malda",
        oldPrice: 1000,
        currentPrice: 800,
        duration: "week",
        rating: 4.9,
        slug: "hairdryer",
        productDetails: "This high-performance hairdryer features multiple heat and speed settings, ensuring a quick and efficient drying experience. Its lightweight design makes it easy to handle, while the sleek look adds style to your grooming routine."
    },
    {
        productId: 9,
        image: "https://picsum.photos/243/236",
        itemName: "Laptop",
        lender: "Dev",
        place: "Canada",
        oldPrice: 10000,
        currentPrice: 9500,
        duration: "day",
        rating: 4.7,
        slug: "laptop",
        productDetails: "This laptop is designed for productivity, offering powerful performance for both work and play. With a high-resolution display and fast processing speed, it's perfect for multitasking and running demanding applications."
    },
];
